spring.application.name=TicketSecure
spring.datasource.url=jdbc:postgresql://localhost:5444/ticketsecure_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.connection-timeout=5000
spring.rabbitmq.template.receive-timeout=5000
ticketsecure.security.qr-salt=${TICKETSECURE_SECURITY_KEY:default-salt}
llm.groq.url=https://api.groq.com/openai/v1/chat/completions
llm.groq.key=${GROQ_API_KEY:}
llm.groq.model=llama-3.1-8b-instant
llm.openrouter.url=https://openrouter.ai/api/v1/chat/completions
llm.openrouter.key=${OPENROUTER_API_KEY:teste}
llm.openrouter.model=nvidia/nemotron-3-super-120b-a12b:free