spring.application.name=TicketSecure

spring.datasource.url=jdbc:postgresql://localhost:5444/ticketsecure_db
spring.datasource.username=admin
spring.datasource.password=adminpassword

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true