version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ticketsecure-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: ticketsecure_db
    ports:
      - "5444:5432"
    volumes:
      - ticketsecure_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ticketsecure-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped


volumes:
  ticketsecure_data: